In [92]:
import numpy as np
import pandas as pd

In [93]:
datos =  pd.read_csv("kc_house_data.csv")
datos.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [94]:
datos['Intercept'] =  1
datos.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...        1180              0   
1      7242     2.0           0     0  ...        2170            400   
2     10000     1.0           0     0  ...         770              0   
3      5000     1.0           0     0  ...        1050            910   
4      8080     1.0           0     0  ...        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  Intercept  
0        5650          1  
1        7639          1  
2        8062          1  
3        5000          1  
4        7503          1  

[5 rows x 22 columns]

In [95]:
datos['year'] = datos['date'].str[:4]

In [135]:
x = datos.drop(['price', 'id', 'date', 'long', 'lat'], axis=1)
y = datos['price'].values

In [136]:
for i, col in enumerate(x.columns):
    print(i, col)

0 bedrooms
1 bathrooms
2 sqft_living
3 sqft_lot
4 floors
5 waterfront
6 view
7 condition
8 grade
9 sqft_above
10 sqft_basement
11 yr_built
12 yr_renovated
13 zipcode
14 sqft_living15
15 sqft_lot15
16 Intercept
17 year


In [137]:
x = datos.drop(['price', 'id', 'date', 'long', 'lat'], axis=1).values.astype(float)

In [138]:
x.shape[1]

18

In [139]:
x.shape[0]

21613

In [140]:
x[:5]

array([[3.0000e+00, 1.0000e+00, 1.1800e+03, 5.6500e+03, 1.0000e+00,
        0.0000e+00, 0.0000e+00, 3.0000e+00, 7.0000e+00, 1.1800e+03,
        0.0000e+00, 1.9550e+03, 0.0000e+00, 9.8178e+04, 1.3400e+03,
        5.6500e+03, 1.0000e+00, 2.0140e+03],
       [3.0000e+00, 2.2500e+00, 2.5700e+03, 7.2420e+03, 2.0000e+00,
        0.0000e+00, 0.0000e+00, 3.0000e+00, 7.0000e+00, 2.1700e+03,
        4.0000e+02, 1.9510e+03, 1.9910e+03, 9.8125e+04, 1.6900e+03,
        7.6390e+03, 1.0000e+00, 2.0140e+03],
       [2.0000e+00, 1.0000e+00, 7.7000e+02, 1.0000e+04, 1.0000e+00,
        0.0000e+00, 0.0000e+00, 3.0000e+00, 6.0000e+00, 7.7000e+02,
        0.0000e+00, 1.9330e+03, 0.0000e+00, 9.8028e+04, 2.7200e+03,
        8.0620e+03, 1.0000e+00, 2.0150e+03],
       [4.0000e+00, 3.0000e+00, 1.9600e+03, 5.0000e+03, 1.0000e+00,
        0.0000e+00, 0.0000e+00, 5.0000e+00, 7.0000e+00, 1.0500e+03,
        9.1000e+02, 1.9650e+03, 0.0000e+00, 9.8136e+04, 1.3600e+03,
        5.0000e+03, 1.0000e+00, 2.0140e+03],
    

In [141]:
y[:5]

array([221900., 538000., 180000., 604000., 510000.])

In [142]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1)

In [148]:
xt_x =  x_train.T @ x_train
xt_x_inv = np.linalg.pinv(xt_x)
xt_y = x_train.T @ y_train

In [149]:
betas = xt_x_inv @ xt_y
betas

array([-3.50222018e+04,  4.29199596e+04,  1.04474396e+02, -2.23784037e-02,
        3.11908428e+04,  5.63820342e+05,  4.18540094e+04,  1.80150846e+04,
        1.19581797e+05,  4.90585410e+01,  5.54277615e+01, -3.55574101e+03,
        1.29637747e+01, -5.47702463e+01,  2.27285267e+01, -4.93959290e-01,
        2.10969938e+01,  5.73223964e+03])

In [150]:
TSS = y_train.T @ y_train - len(y_train) * y_train.mean()**2
ESS = betas.T @ x_train.T @ ( x_train @ betas) - len(y_train) * y_train.mean()**2
RSS = TSS - ESS 

R2 = 1 - (RSS / TSS)
print("R2:", R2)

R2: 0.6530086442339124


In [146]:
import statsmodels.api as sm
regressor = sm.OLS(y_train, x_train).fit()

In [122]:
regressor.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.654
Model:                            OLS   Adj. R-squared:                  0.653
Method:                 Least Squares   F-statistic:                     1783.
Date:                Fri, 02 May 2025   Prob (F-statistic):               0.00
Time:                        15:25:42   Log-Likelihood:            -2.0677e+05
No. Observations:               15129   AIC:                         4.136e+05
Df Residuals:                   15112   BIC:                         4.137e+05
Df Model:                          16                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1         -3.473e+04   2311.969    -15.021      0.000   -3.93e+04   -3.02e+04
x2          4.297e+04   4034.306     10.650      0.000    3.51e+04    5.09e+04
x3           104.2019      2.845     36.629      0.000      98.626     109.778
x4            -0.0196      0.056     -0.350      0.727      -0.129       0.090
x5          2.979e+04   4441.455      6.707      0.000    2.11e+04    3.85e+04
x6          5.654e+05   2.14e+04     26.434      0.000    5.23e+05    6.07e+05
x7          4.096e+04   2639.495     15.516      0.000    3.58e+04    4.61e+04
x8          1.976e+04   2915.759      6.777      0.000     1.4e+04    2.55e+04
x9          1.194e+05   2615.434     45.668      0.000    1.14e+05    1.25e+05
x10           49.5621      2.767     17.915      0.000      44.139      54.985
x11           54.6382      3.261     16.757      0.000      48.247      61.030
x12        -3487.2321     86.097    -40.504      0.000   -3655.992   -3318.472
x13           14.1645      4.541      3.120      0.002       5.264      23.065
x14           31.2502     36.261      0.862      0.389     -39.825     102.326
x15           24.5057      4.238      5.782      0.000      16.198      32.813
x16           -0.4851      0.088     -5.517      0.000      -0.657      -0.313
const      -4.332e+07   8.18e+06     -5.294      0.000   -5.94e+07   -2.73e+07
x17         2.298e+04   3630.658      6.329      0.000    1.59e+04    3.01e+04
==============================================================================
Omnibus:                     9441.865   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           328963.689
Skew:                           2.458   Prob(JB):                         0.00
Kurtosis:                      25.309   Cond. No.                     1.66e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.59e-21. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

### Aqui podemos ver que la columna 4 como la 14, en enumeracion al inicio son 3 sqft_lot, 13 zipcode, no son relevantes para el modelo, se pueden eliminar. Al igual que los dos modelos son identicos por la r2.